== Neo4j Movies Application: Quick Start

image::https://github.com/neo4j-examples/movies-dotnetcore-bolt/workflows/.NET/badge.svg[CI]

== The Stack

These are the components of our Web Application:

* Application Type:         .NET Core Application.
* Web framework:            https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-6.0[ASP.NET core]
* Neo4j Database Connector: https://github.com/neo4j/neo4j-dotnet-driver/[Neo4j .NET Driver] for working with Cypher
** https://neo4j.com/docs/getting-started/current/languages-guides/neo4j-dotnet/[Driver docs]
** https://neo4j.com/docs/getting-started/current/cypher-intro/[Cypher docs]
* Database:                 Neo4j-Server 3.5, 4.X/5.X with multi-database
* Frontend:                 jquery, bootstrap, https://d3js.org/[d3.js]

Provision a database quickly with https://sandbox.neo4j.com/?usecase=movies[Neo4j Sandbox] or https://neo4j.com/cloud/aura/[Neo4j Aura].

== Endpoints:

Get Movie

----
// JSON object for single movie with cast
curl http://BASE_URL/movie/The%20Matrix

// list of JSON objects for movie search results
curl http://BASE_URL/search?q=matrix

// JSON object for whole graph viz (nodes, links - arrays)
curl http://BASE_URL/graph
----

== Setup

This uses the ASP.NET core framework, along with the official Neo4j .NET driver.

== Run:

Start this application with:

[source,shell]
----
dotnet run
----

Go to http://localhost:8080

You can search for movies by title or and click on any entry.

== Configuration options

NOTE: These are preferably configured via `Properties/launchSettings.json`.

[%header,cols=2*]
|===
|Environment variable name
|Default value (or N/A)

|PORT
|8080

|NEO4J_URI
|neo4j+s://demo.neo4jlabs.com

|NEO4J_USER
|movies

|NEO4J_PASSWORD
|movies

|NEO4J_DATABASE
|movies

|NEO4J_VERSION
|4
|===

Please set `NEO4J_VERSION` to `3.5` when running Neo4j 3.5.x. Leave as is otherwise.

To run the database locally as well, start your local Neo4j Server (https://neo4j.com/download[Download & Install]), open Neo4j Browser.
Then install the Movies data-set with `:play movies`, click the statement, and hit the triangular "Run" button.

Then, override the relevant environment variables above.
